---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  eval = FALSE,
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# AI4Medicine

<!-- badges: start -->
<!-- badges: end -->

The goal of AI4Medicine is to ...

## Installation

```{r}
# install.packages("devtools")
devtools::install_github("jixing475/AI4Medicine")
```

# set env
```{bash }
conda create -n AI4Medicine  python=3.7  pyarrow ipykernel -y
conda activate AI4Medicine

# week 1
pip install pandas numpy matplotlib seaborn tensorflow keras
```


```{bash}
# 激活虚拟环境
conda activate AI4Medicine

# create notebook kernel connected with the conda environment
# 如果没有ipykernel模块, 运行以下代码
# conda install -c anaconda ipykernel -y
python -m ipykernel install --user --name AI4Medicine  --display-name "AI4Medicine"
```

# download data to local
```{r setup}
# library(AI4Medicine)
```
```{bash engine.opts='-i'}
cd analysis/notebooks/Diagnosis/M1/nih

wget https://wwlhugij.labs.coursera.org/edit/M1/nih/data.tar.gz 
wget https://wwlhugij.labs.coursera.org/edit/M1/nih/densenet.hdf5 
wget https://wwlhugij.labs.coursera.org/edit/M1/nih/images-small
wget https://wwlhugij.labs.coursera.org/edit/M1/nih/pretrained_model.h5 
wget https://wwlhugij.labs.coursera.org/edit/M1/nih/pretrained_model_old.h5 
wget https://wwlhugij.labs.coursera.org/edit/M1/nih/test.csv
wget https://wwlhugij.labs.coursera.org/edit/M1/nih/train-all.csv
wget https://wwlhugij.labs.coursera.org/edit/M1/nih/train-small.csv
wget https://wwlhugij.labs.coursera.org/edit/M1/nih/train-small-new.csv
wget https://wwlhugij.labs.coursera.org/edit/M1/nih/train-toy.csv
wget https://wwlhugij.labs.coursera.org/edit/M1/nih/valid-all.csv
wget https://wwlhugij.labs.coursera.org/edit/M1/nih/valid-small.csv
wget https://wwlhugij.labs.coursera.org/edit/M1/nih/valid-toy.csv
```

# M1

## AI4M_C1_W1_lecture_ex_01

[AI4M_C1_W1_lecture_ex_01](https://wwlhugij.labs.coursera.org/notebooks/M1/AI4M_C1_W1_lecture_ex_01.ipynb#)

```{r}
options(rmarkdown.html_vignette.check_title = FALSE) 
manuscriptsR::ipynb_to_rmd("vignettes/AI4M_C1_W1_lecture_ex_01.ipynb")
#usethis::use_vignette("AI4M_C1_W1_lecture_ex_01")
pkgdown::build_article("AI4M_C1_W1_lecture_ex_01")
#pkgdown::build_site()
```



# Misc

查找课程 jupyter notebook 的代码: 

https://github.com/search?q=AI4M_C1&type=commits

